version: '3.7'

services:

  web:
    build:
      context: ./nginx
    # cap and privileged needed for slowlog
    # restart: always
    cap_add:
      - CAP_SYS_PTRACE
    privileged: true
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/access.log:/var/log/nginx/access.log
      - ./nginx/logs/error.log:/var/log/nginx/error.log
      - ./Demo:/var/www/html
    env_file:
      - ./nginx/.env
      - ./nginx/dev.env
    depends_on:
      - app

  app:
    build:
      context: ./php
    # restart: always
    cap_add:
      - CAP_SYS_PTRACE
    privileged: true
    expose:
      - 9000
    volumes:
      - ./Demo:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/php.dev.ini:/usr/local/etc/php/conf.d/php.dev.ini
      - ./php/logs/xdebug.log:/tmp/xdebug.log
      - ./php/logs/error.log:/tmp/php.error.log
      - ./php/logs/debug:/tmp/debug
    env_file:
      - ./php/.env
      - ./php/dev.env

networks:
  default:
    external:
      name: webservices
